### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by jcf**
This an optional extra on top of the work in #2.

I don't want to force CI on the project, and don't want to mandate a particular provider. This certainly helped me make sure everything worked properly on a machine other than my own, which is often handy.

Please feel free to ignore/accept/close as you see fit.

### CODE REVIEW

**Comment by jcf** [comment]
I was going to add a build status badge to the README but figured I haven't had a :+1: on setting up CI.

When I looked at the README I noticed the same paragraph (more or less) duplicated at the start. Didn't know whether or not to create an issue.

**Comment by whilo** [comment]
This looks fine to me. Go ahead with the badge, if you like :) I haven't done CI yet, but think it is a good idea. You can also replace the first paragraph by the third one.

**Comment by jcf** [comment]
> You can also replace the first paragraph by the third one.

@whilo if I get a chance! I had some time yesterday evening, but not sure I will tonight. :smile:

**Comment by whilo** [comment]
Thanks a lot! :)

**Pull request merged**
